Update WebApi routes for security and RESTful best practices
microsoft/chat-copilot pull request #417
Opened 2023-09-29 04:11 UTC by glahaye

### Motivation and Context
The REST routes have grown organically and don't represent the best REST practices.
Also, user ID is sometimes taken from routes instead of verified tokens.
This PR is to address these two points.

### Description
- Changed routes
- Renamed classes accordingly
- Hid chat archive (formally "bot") schema settings from user
- Simplified IContentSafetyService interface and related dependency injection
- Removed ConfigureAwait(false) instances (they have no effect in ASP.Net Core apps)
- Moved isContentSafetyEnabled to ServiceOptions

### Contribution Checklist
- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [Contribution Guidelines](https://github.com/microsoft/chat-copilot/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/chat-copilot/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

2023-10-02 16:06 UTC, dehoward requested changes

2023-10-02 16:38 UTC, crickman commented on webapp/src/libs/services/BotService.ts
> +                commandPath: 'chats/archives',
Yes, import/upload isn't currently supported.

https://github.com/microsoft/chat-copilot/issues/342

2023-10-02 16:52 UTC, crickman approved these changes
Checked areas for which I am familiar (memory stuff)...looks good.,

2023-10-02 19:47 UTC, alliscode commented on webapi/Skills/ChatSkills/SemanticMemoryRetriever.cs
> -            await SearchMemoryAsync(memoryName).ConfigureAwait(false);
ASP.NET Core does not have a SynchronizationContext so ConfigureAwait doesn't do anything, it's basically a no-op.

2023-10-02 23:47 UTC, glahaye commented on webapi/Controllers/ChatController.cs
>          this._logger.LogDebug("/chat request received.");
Done

2023-10-02 23:48 UTC, glahaye commented on webapi/Controllers/ChatArchiveController.cs
> +        var memory = await this.CreateChatArchiveAsync(chatId, cancellationToken);
Taken in

2023-10-02 23:50 UTC, glahaye commented on webapi/Controllers/ChatController.cs
> +    [Route("pluginManifest")]
Done

2023-10-02 23:51 UTC, glahaye commented on webapi/Controllers/ServiceInfoController.cs
>      public IActionResult GetServiceOptions()
Done

2023-10-02 23:55 UTC, TaoChenOSU commented on webapi/Controllers/ChatController.cs
>          this._logger.LogDebug("/chat request received.");
And should we downgrade this to a trace message?

2023-10-02 23:55 UTC, TaoChenOSU commented on webapi/Controllers/ChatController.cs
> +    [Route("pluginManifest")]
This has been moved to a new plugin controller.

2023-10-02 23:57 UTC, glahaye commented on webapi/Options/ChatArchiveSchemaInfo.cs
> +    public string Name { get; init; } = "CopilotChat";
This is for serialization of chat archives.  I'm just making the default what we currently use. I don't anticipate this changing soon (or ever, for that matter)

2023-10-03 00:01 UTC, glahaye commented on webapp/src/libs/services/BotService.ts
> +                commandPath: 'chats/archives',
The client will be ready when the route does materialize!

2023-10-03 00:03 UTC, glahaye commented on webapi/Controllers/ChatController.cs
> +        [FromBody] ExecutePlanParameters ask,
Done

2023-10-03 00:43 UTC, glahaye commented on webapi/Controllers/ChatArchiveController.cs
> +    [Route("chats/archives/{chatId:guid}")]
I agree with @dehoward 

@alliscode although your proposal is interesting, going with what Desmond suggests keeps everything uniform and introduces fewer ways of thinking about our collections.

If everybody is cool with "chats/{chatId:guid}/archive", I'll go with that.

2023-10-03 18:14 UTC, alliscode approved these changes

2023-10-03 18:44 UTC, dehoward approved these changes

2023-10-03 18:46 UTC, merged