Issue 428
microsoft/chat-copilot pull request #446
Opened 2023-10-03 17:54 UTC by arnoldblake

### Motivation and Context

This pull request introduces an enhancement to the deploy-webapi and deploy-webapp scripts by enabling the optional use of Azure App Service Deployment Slots and Static Web App Preview Environments respectively. This feature addresses the challenge of achieving zero-downtime deployments, ensuring that our application remains accessible and functional during updates. Deployment slots allow us to validate application changes in a staging environment that mirrors production, facilitating extensive testing and verification before the swap. This guarantees that only thoroughly vetted and approved changes reach the live environment, enhancing our deployment confidence and application reliability. Moreover, in the rare case of an issue arising post-deployment, the slots provide an instant rollback mechanism, minimizing disruption and ensuring continuity of service for our users.

### Description

Both scripts were modified to allow an optional parameter for either a deployment slot or preview environment. The scripts behavior is unchanged if these parameters are not present. 

deploy-webapi
Code was introduced which checks for the existence of a deployment slot. Following other script behavior if the deployment slot does not exist it is created. 

deploy-webapp
Modified the command swa deploy to support the environment parameter which defaults to production if not present. Added a loop to check each preview environment URL is present in the CORS and AAD app registration.

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [Contribution Guidelines](https://github.com/microsoft/chat-copilot/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/chat-copilot/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

2023-10-03 18:43 UTC, glahaye commented on scripts/deploy/deploy-webapi.ps1
> +    $availableSlots = az webapp deployment slot list --resource-group utverse-devl --name app-utverse-devl-webapi | ConvertFrom-JSON | Select-Object -Property Name
utverse-devl???  That should be replaced by the param to this script! Same at line 80.

2023-10-03 19:01 UTC, glahaye commented on scripts/deploy/deploy-webapi.sh
> +    echo "  -o, --slot DEPLOYMENT_SLOT                      Name of the target web app deployment slot"
Please line this up with the other descriptions above

2023-10-03 19:05 UTC, glahaye commented on scripts/deploy/deploy-webapi.sh
> +        az webapp deployment slot create --slot $DEPLOYMENT_SLOT --resource-group $RESOURCE_GROUP --name $WEB_APP_NAME > /dev/null 2>&1
Are you sure you want to redirect BOTH stdout and stderr to null?

2023-10-03 20:26 UTC, glahaye commented on scripts/deploy/deploy-webapp.sh
> +APPNAME="swa-utverse-devl"
This hardcoded value should not be here...

2023-10-03 20:28 UTC, glahaye requested changes
Some hardcoded values were left in the scripts - They should be replaced with the appropriate parameter value

2023-10-04 00:21 UTC, glahaye submitted a review, later dismissed

2023-10-04 00:22 UTC, glahaye commented
Just sync with latest and resolve the conflicts and this PR is good to go

2023-10-04 10:16 UTC, arnoldblake commented
@microsoft-github-policy-service agree

2023-10-04 10:25 UTC, arnoldblake commented
Will the commits be squashed when they are merged?

2023-10-04 17:01 UTC, glahaye commented
> Will the commits be squashed when they are merged? Should I squash them myself? How would that impact the pull request?

They will be squashed. Please don't waste time doing that yourself! :)

2023-10-04 17:53 UTC, glahaye approved these changes

2023-10-04 18:10 UTC, merged